### ISSUE TITLE
New AWS AMI, trying to find non-existing /home/ubuntu/save

### ISSUE THREAD

**Issue by jajajaqlt** [capergroup/bayou#123]
Got some weird errors when trying to run the ast_quality_perf_test.py. Basically, the machine is trying to find files under /home/ubuntu/save, which never exists. Have people encountered this before? 

```
ubuntu@ip-172-30-3-192:~/bayou/src/main/python/bayou/validation$ ./main-auto.sh 27
current time is 2017-11-11-00-10-13
script, model, data directory is /home/ubuntu/bayou/src/main/python
python path is /home/ubuntu/bayou/src/main/python
DATA-validation.json
DATA_STEM is DATA-validation
finish splitting files into 1 pieces
finish moving splits
Waiting for processes to finish...
1
Namespace(evidence='all', input_file=['splits/DATA-validation-00.json'], output_file='out_asts/out_asts_1.json', python_recursion_limit=10000, save='model-27/')
2017-11-11 00:10:21.820974: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
NVIDIA: no NVIDIA devices found
2017-11-11 00:10:21.836749: E tensorflow/stream_executor/cuda/cuda_driver.cc:406] failed call to cuInit: CUDA_ERROR_UNKNOWN
2017-11-11 00:10:21.836814: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:145] kernel driver does not appear to be running on this host (ip-172-30-3-192): /proc/driver/nvidia/version does not exist
Loading model...
2017-11-11 00:10:23.495660: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.495685: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.495710: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.495750: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.495755: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.495774: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.495784: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.495814: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.495825: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.495852: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.495875: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.495887: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.495870: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.495916: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.495901: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.495963: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.495943: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.495922: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.495945: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496027: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.495989: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.495991: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496092: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496115: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496128: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496146: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496180: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496197: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496000: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496220: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.495964: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496049: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496257: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496075: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496188: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496226: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496159: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496311: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496345: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496285: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496341: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496310: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496377: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496424: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496400: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496485: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496506: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496514: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496530: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496455: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496559: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496429: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496595: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496372: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496541: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496584: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496669: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496694: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496664: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496732: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496616: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496639: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496779: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496722: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496745: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496772: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496851: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496866: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496891: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496913: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496825: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496952: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496974: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496984: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496999: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496797: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.497031: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496960: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496822: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496938: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.497104: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.497015: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.497057: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.496898: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.497065: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
2017-11-11 00:10:23.497088: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
	 [[Node: save/RestoreV2_2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_2/tensor_names, save/RestoreV2_2/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../bayou/test/ast_quality_perf_test.py", line 94, in <module>
    ast_quality_perf_test(clargs)
  File "../../bayou/test/ast_quality_perf_test.py", line 45, in ast_quality_perf_test
    predictor = model(clargs.save, sess)  # create a predictor that can generates ASTs from evidence
  File "/home/ubuntu/bayou/src/main/python/bayou/models/low_level_evidences/infer.py", line 45, in __init__
    saver.restore(self.sess, ckpt.model_checkpoint_path)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/training/saver.py", line 1666, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
	 [[Node: save/RestoreV2_2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_2/tensor_names, save/RestoreV2_2/shape_and_slices)]]

Caused by op 'save/RestoreV2_2', defined at:
  File "../../bayou/test/ast_quality_perf_test.py", line 94, in <module>
    ast_quality_perf_test(clargs)
  File "../../bayou/test/ast_quality_perf_test.py", line 45, in ast_quality_perf_test
    predictor = model(clargs.save, sess)  # create a predictor that can generates ASTs from evidence
  File "/home/ubuntu/bayou/src/main/python/bayou/models/low_level_evidences/infer.py", line 43, in __init__
    saver = tf.train.Saver(tf.global_variables())
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/training/saver.py", line 1218, in __init__
    self.build()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/training/saver.py", line 1227, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/training/saver.py", line 1263, in _build
    build_save=build_save, build_restore=build_restore)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/training/saver.py", line 751, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/training/saver.py", line 427, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/training/saver.py", line 267, in restore_op
    [spec.tensor.dtype])[0])
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 1021, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ubuntu/save/model49.ckpt: Not found: /home/ubuntu/save; No such file or directory
	 [[Node: save/RestoreV2_2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_2/tensor_names, save/RestoreV2_2/shape_and_slices)]]

1
1
^C
ubuntu@ip-172-30-3-192:~/bayou/src/main/python/bayou/validation$ ls
ast_quality_perf_test-1.0-jar-with-dependencies.jar  main-auto.sh  out_asts  validate-auto.sh
DATA-validation.json                                 model-27      splits
ubuntu@ip-172-30-3-192:~/bayou/src/main/python/bayou/validation$ vim ~/aws_on_boot.sh 
ubuntu@ip-172-30-3-192:~/bayou/src/main/python/bayou/validation$ echo $LD_LIBRARY_PATH
/home/ubuntu/cuda/lib64:/usr/local/cuda-8.0/lib64::/usr/local/cuda/lib64
ubuntu@ip-172-30-3-192:~/bayou/src/main/python/bayou/validation$ ls ~
aws_on_boot.sh  bayou  cuda  cudnn-8.0-linux-x64-v6.0.tgz
ubuntu@ip-172-30-3-192:~/bayou/src/main/python/bayou/validation$ echo $PYTHONPATH
/home/ubuntu/bayou/src/main/python
ubuntu@ip-172-30-3-192:~/bayou/src/main/python/bayou/validation$ ls
ast_quality_perf_test-1.0-jar-with-dependencies.jar  main-auto.sh  out_asts  validate-auto.sh
DATA-validation.json                                 model-27      splits
ubuntu@ip-172-30-3-192:~/bayou/src/main/python/bayou/validation$ ls model-27/
checkpoint                        model24.ckpt.meta                 model40.ckpt.data-00000-of-00001
config.json                       model25.ckpt.data-00000-of-00001  model40.ckpt.index
model0.ckpt.data-00000-of-00001   model25.ckpt.index                model40.ckpt.meta
model0.ckpt.index                 model25.ckpt.meta                 model41.ckpt.data-00000-of-00001
model0.ckpt.meta                  model26.ckpt.data-00000-of-00001  model41.ckpt.index
model10.ckpt.data-00000-of-00001  model26.ckpt.index                model41.ckpt.meta
model10.ckpt.index                model26.ckpt.meta                 model42.ckpt.data-00000-of-00001
model10.ckpt.meta                 model27.ckpt.data-00000-of-00001  model42.ckpt.index
model11.ckpt.data-00000-of-00001  model27.ckpt.index                model42.ckpt.meta
model11.ckpt.index                model27.ckpt.meta                 model43.ckpt.data-00000-of-00001
model11.ckpt.meta                 model28.ckpt.data-00000-of-00001  model43.ckpt.index
model12.ckpt.data-00000-of-00001  model28.ckpt.index                model43.ckpt.meta
model12.ckpt.index                model28.ckpt.meta                 model44.ckpt.data-00000-of-00001
model12.ckpt.meta                 model29.ckpt.data-00000-of-00001  model44.ckpt.index
model13.ckpt.data-00000-of-00001  model29.ckpt.index                model44.ckpt.meta
model13.ckpt.index                model29.ckpt.meta                 model45.ckpt.data-00000-of-00001
model13.ckpt.meta                 model2.ckpt.data-00000-of-00001   model45.ckpt.index
model14.ckpt.data-00000-of-00001  model2.ckpt.index                 model45.ckpt.meta
model14.ckpt.index                model2.ckpt.meta                  model46.ckpt.data-00000-of-00001
model14.ckpt.meta                 model30.ckpt.data-00000-of-00001  model46.ckpt.index
model15.ckpt.data-00000-of-00001  model30.ckpt.index                model46.ckpt.meta
model15.ckpt.index                model30.ckpt.meta                 model47.ckpt.data-00000-of-00001
model15.ckpt.meta                 model31.ckpt.data-00000-of-00001  model47.ckpt.index
model16.ckpt.data-00000-of-00001  model31.ckpt.index                model47.ckpt.meta
model16.ckpt.index                model31.ckpt.meta                 model48.ckpt.data-00000-of-00001
model16.ckpt.meta                 model32.ckpt.data-00000-of-00001  model48.ckpt.index
model17.ckpt.data-00000-of-00001  model32.ckpt.index                model48.ckpt.meta
model17.ckpt.index                model32.ckpt.meta                 model49.ckpt.data-00000-of-00001
model17.ckpt.meta                 model33.ckpt.data-00000-of-00001  model49.ckpt.index
model18.ckpt.data-00000-of-00001  model33.ckpt.index                model49.ckpt.meta
model18.ckpt.index                model33.ckpt.meta                 model4.ckpt.data-00000-of-00001
model18.ckpt.meta                 model34.ckpt.data-00000-of-00001  model4.ckpt.index
model19.ckpt.data-00000-of-00001  model34.ckpt.index                model4.ckpt.meta
model19.ckpt.index                model34.ckpt.meta                 model5.ckpt.data-00000-of-00001
model19.ckpt.meta                 model35.ckpt.data-00000-of-00001  model5.ckpt.index
model1.ckpt.data-00000-of-00001   model35.ckpt.index                model5.ckpt.meta
model1.ckpt.index                 model35.ckpt.meta                 model6.ckpt.data-00000-of-00001
model1.ckpt.meta                  model36.ckpt.data-00000-of-00001  model6.ckpt.index
model20.ckpt.data-00000-of-00001  model36.ckpt.index                model6.ckpt.meta
model20.ckpt.index                model36.ckpt.meta                 model7.ckpt.data-00000-of-00001
model20.ckpt.meta                 model37.ckpt.data-00000-of-00001  model7.ckpt.index
model21.ckpt.data-00000-of-00001  model37.ckpt.index                model7.ckpt.meta
model21.ckpt.index                model37.ckpt.meta                 model8.ckpt.data-00000-of-00001
model21.ckpt.meta                 model38.ckpt.data-00000-of-00001  model8.ckpt.index
model22.ckpt.data-00000-of-00001  model38.ckpt.index                model8.ckpt.meta
model22.ckpt.index                model38.ckpt.meta                 model9.ckpt.data-00000-of-00001
model22.ckpt.meta                 model39.ckpt.data-00000-of-00001  model9.ckpt.index
model23.ckpt.data-00000-of-00001  model39.ckpt.index                model9.ckpt.meta
model23.ckpt.index                model39.ckpt.meta                 model.pb
model23.ckpt.meta                 model3.ckpt.data-00000-of-00001   model.pbtxt
model24.ckpt.data-00000-of-00001  model3.ckpt.index                 train.out
model24.ckpt.index                model3.ckpt.meta
ubuntu@ip-172-30-3-192:~/bayou/src/main/python/bayou/validation$ 
```

**Comment by vijay-murali** [comment]
There was an issue in the model file that caused this. I have fixed the model file (in S3) so this problem should be gone. I will investigate what caused the issue in the first place.

**Comment by vijay-murali** [comment]
I'm closing this, as the issue was with a command line parameter specified in one of the training rounds that creeped into the model file. This should not arise in future, but if it does feel free to re-open.
